services:
  - type: web
    name: n8n-free
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        sync: false
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        sync: false
      - key: GENERIC_TIMEZONE
        value: America/Argentina/Buenos_Aires
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
